<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { getBehaviorTree } from '../api/modules/behaviors'
import type { BehaviorTreeDefinition } from '../types/domain'
const route=useRoute(); const router=useRouter(); const tree=ref<BehaviorTreeDefinition|null>(null); const selectedId=ref<string|null>(null); const libraryTab=ref<'subtrees'|'nodes'>('subtrees')
const fallback=():BehaviorTreeDefinition=>({id:route.params.id as string,name:route.query.name as string||'未命名结构',version:'v0.1',taskType:route.query.kind==='subtree'?'可复用流程':'成品转运',status:'草稿',updatedAt:'2026-08-15 13:40',nodeCount:1,kind:route.query.kind==='subtree'?'subtree':'behavior',summary:'尚未配置',references:'未引用',nodes:[{id:'root',name:route.query.name as string||'根节点',kind:'sequence',x:360,y:70}]})
onMounted(async()=>{try{tree.value=await getBehaviorTree(route.params.id as string)}catch{tree.value=fallback()}})
</script>
<template><section v-if="tree" class="editor-page"><header class="editor-topbar"><div><button @click="router.push('/behaviors')">←</button><span>行为树列表 / <strong>{{ tree.name }}</strong></span><em>{{ tree.kind==='subtree'?'子树 · 不可独立执行':'行为树 · 可绑定任务' }}</em></div><div><button>保存草稿</button><button>校验流程</button><button class="primary">发布</button></div></header><div class="behavior-editor-shell"><aside class="editor-library"><header>节点库</header><nav><button :class="{active:libraryTab==='subtrees'}" @click="libraryTab='subtrees'">子树</button><button :class="{active:libraryTab==='nodes'}" @click="libraryTab='nodes'">基础节点</button></nav><template v-if="libraryTab==='subtrees'"><button><i>ST</i><span><strong>标准取料单元</strong><small>ST-001 · 已发布</small></span></button><button><i>ST</i><span><strong>缓冲区交付单元</strong><small>ST-002 · 草稿</small></span></button><button><i>ST</i><span><strong>安全回充单元</strong><small>ST-003 · 已发布</small></span></button></template><template v-else><button><i>→</i><span><strong>顺序执行</strong><small>Sequence</small></span></button><button><i>?</i><span><strong>条件节点</strong><small>判断设备或任务状态</small></span></button><button><i>N</i><span><strong>导航至设备</strong><small>Navigate</small></span></button><button><i>W</i><span><strong>等待设备信号</strong><small>Wait signal</small></span></button></template></aside><main class="behavior-canvas"><div class="canvas-caption">{{ tree.id }} / {{ tree.taskType }}</div><div class="canvas-tools"><button class="active">选择</button><button>连线</button><button>−</button><button>100%</button><button>＋</button></div><svg viewBox="0 0 720 420"><g class="tree-connectors"><path v-for="node in tree.nodes.filter(n=>n.parentId)" :key="node.id" :d="`M360 105V145H${node.x}V162`"/></g><g v-for="node in tree.nodes" :key="node.id" :class="['editor-node',node.kind,{selected:selectedId===node.id}]" :transform="`translate(${node.x} ${node.y})`" @click="selectedId=node.id"><rect x="-72" y="-28" width="144" height="56" rx="5"/><text y="4">{{ node.name }}</text></g></svg><footer class="editor-validation"><strong>基础结构完整</strong><span>{{ tree.nodeCount }} 个节点</span><span>{{ Math.max(0,tree.nodeCount-1) }} 条连接</span></footer></main><aside class="editor-properties"><header>节点属性</header><template v-if="selectedId"><label>节点名称<input :value="tree.nodes.find(n=>n.id===selectedId)?.name"></label><label>节点编号<input :value="selectedId"></label><label>失败处理<select><option>终止任务</option><option>重试当前节点</option></select></label><label>超时时间<input value="60 秒"></label><button class="danger">删除节点</button></template><div v-else class="empty-inspector"><b>未选择节点</b><span>点击画布节点查看属性；从左侧拖入子树或基础节点扩展流程。</span></div></aside></div></section></template>
